/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Defines whether argp.h exists */
#define HAVE_ARGP 1

/* Defines if stdlib has function clearenv */
#define HAVE_CLEARENV 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Defines whether Firebird 2.x is installed */
/* #undef HAVE_FIREBIRD2 */

/* Define if you have the iconv() function. */
#define HAVE_ICONV 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Defines if stdc++ library contains a <iostream> implementation */
#define HAVE_IOSTREAM 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Defines if Mysql has the mysql_real_escape_string function */
/* #undef HAVE_MYSQL_REAL_ESCAPE_STRING */

/* Defined if stdc++ library does not contain a sstream implementation */
/* #undef HAVE_NO_SSTREAM */

/* Define if you have the development files for python */
#define HAVE_PYTHON 1

/* Defines if stdc++ library contains a sstream implementation */
#define HAVE_SSTREAM 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define as const if the declaration of iconv() needs const. */
#define ICONV_CONST 

/* Defines that stdc++ library does not have a new <iostream> implementation
   */
/* #undef NO_IOSTREAM */

/* DEFINES THE NAME OF THE ODBC LIBRARY */
#define ODBCLIBRARY "odbc"

/* Name of package */
#define PACKAGE "hk_classes"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* pxlib build date */
#define PXLIB_BUILD_DATE "2020-02-16"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.8.4"
